language: node_js
node_js:
  - "6.1"
branches:
  only:
  - version
env:
  global:
  - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
  - COMMIT_AUTHOR_EMAIL: "cedric.burceaux@gmail.com"
before_install:
  - ./deploy-prod-travis.sh
script:
  - 